name: flutter_banergy
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5
  #flutter_tesseract_ocr: ^0.4.24
  path_provider: ^2.1.1
  qr_bar_code_scanner_dialog: ^0.0.5
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.1.1
  animated_switcher_plus: ^1.1.0
  beamer: ^0.14.1
  permission_handler: ^11.1.0
  camera: ^0.10.5+9
  image_gallery_saver: ^2.0.3
  http: ^1.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  crypto: ^3.0.3
  image: ^3.0.1
  dio: ^5.4.1
  photo_view: ^0.15.0
  intl: ^0.19.0
  # photo_view: ^0.12.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
    - assets/tessdata/
    - images/
  uses-material-design: true

  fonts:
   - family: PretendardBold
     fonts:
       - asset: assets/fonts/Pretendard-Bold.otf
   - family: PretendardSemiBold
     fonts:
       - asset: assets/fonts/Pretendard-SemiBold.otf
   - family: PretendardRegular
     fonts:
       - asset: assets/fonts/Pretendard-Regular.otf
   - family: PretendardMedium
     fonts:
       - asset: assets/fonts/Pretendard-Medium.otf
   - family: PretendardLight
     fonts:
       - asset: assets/fonts/Pretendard-Light.otf
